# Generated by Django 5.1.6 on 2025-03-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents_sheet',
            name='child_day_of_birth',
            field=models.CharField(blank=True, default='', max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='parents_sheet',
            name='father_day_of_birth',
            field=models.CharField(blank=True, default='', max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='parents_sheet',
            name='mother_day_of_birth',
            field=models.CharField(blank=True, default='', max_length=75, null=True),
        ),
    ]
