# Generated by Django 5.1.6 on 2025-03-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_alter_parents_sheet_child_day_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents_sheet',
            name='child_speech_therapy_advise',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
    ]
