# Generated by Django 5.1.6 on 2025-03-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0003_alter_parents_sheet_child_speech_therapy_advise'),
    ]

    operations = [
        migrations.AddField(
            model_name='parents_sheet',
            name='child_comments_1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='parents_sheet',
            name='child_comments_2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='parents_sheet',
            name='child_comments_3',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='parents_sheet',
            name='child_comments_4',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='parents_sheet',
            name='child_comments_5',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='parents_sheet',
            name='child_comments_6',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
