# Generated by Django 5.1.6 on 2025-03-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0004_parents_sheet_child_comments_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parents_sheet',
            name='sheet_created',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
