# Generated by Django 5.1.6 on 2025-03-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0005_parents_sheet_sheet_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents_sheet',
            name='crawl_age_advise',
            field=models.CharField(choices=[('verspätet', 'Verspaetet'), ('altersgerecht', 'Altersgerecht')], max_length=20),
        ),
        migrations.AlterField(
            model_name='parents_sheet',
            name='walk_age_advise',
            field=models.CharField(choices=[('verspätet', 'Verspaetet'), ('altersgerecht', 'Altersgerecht')], max_length=20),
        ),
    ]
