# Generated by Django 5.1.6 on 2025-03-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0006_alter_parents_sheet_crawl_age_advise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents_sheet',
            name='crawl_age_advise',
            field=models.CharField(choices=[('unbekannt', 'keine Auswahl'), ('verspaetet', 'verspätet'), ('altersgerecht', 'altersgerecht')], default='unbekannt', max_length=20),
        ),
        migrations.AlterField(
            model_name='parents_sheet',
            name='walk_age_advise',
            field=models.CharField(choices=[('unbekannt', 'keine Auswahl'), ('verspaetet', 'verspätet'), ('altersgerecht', 'altersgerecht')], default='unbekannt', max_length=20),
        ),
    ]
