# Generated by Django 5.1.6 on 2025-03-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0007_alter_parents_sheet_crawl_age_advise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents_sheet',
            name='child_use_of_language',
            field=models.CharField(choices=[('viel', 'viel'), ('weniger', 'weniger'), ('kaum', 'kaum'), ('gar_nicht', 'gar nicht')], default='weniger', max_length=20),
        ),
    ]
