# Generated by Django 5.1.6 on 2025-03-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0008_alter_parents_sheet_child_use_of_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='parents_sheet',
            name='child_stranger',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
