# Generated by Django 5.1.6 on 2025-03-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0009_parents_sheet_child_stranger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents_sheet',
            name='child_gestik',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='parents_sheet',
            name='child_mimik',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='parents_sheet',
            name='child_stranger',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='parents_sheet',
            name='child_understanding',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
