# Generated by Django 5.1.6 on 2025-03-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0010_alter_parents_sheet_child_gestik_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents_sheet',
            name='child_day_of_birth',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='parents_sheet',
            name='father_day_of_birth',
            field=models.DateField(default='1950-01-01'),
        ),
        migrations.AlterField(
            model_name='parents_sheet',
            name='mother_day_of_birth',
            field=models.DateField(default='1950-01-01'),
        ),
    ]
