# Generated by Django 5.1.6 on 2025-03-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0012_alter_parents_sheet_child_day_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents_sheet',
            name='child_day_of_birth',
            field=models.DateField(blank=True, default='2000-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='parents_sheet',
            name='father_day_of_birth',
            field=models.DateField(blank=True, default='1950-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='parents_sheet',
            name='mother_day_of_birth',
            field=models.DateField(blank=True, default='1950-01-01', null=True),
        ),
    ]
