# Generated by Django 5.1.6 on 2025-04-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0013_alter_parents_sheet_child_day_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parents_sheet',
            name='child_school_which',
        ),
        migrations.RemoveField(
            model_name='parents_sheet',
            name='child_school_yes',
        ),
        migrations.AddField(
            model_name='parents_sheet',
            name='child_dev_5_yes',
            field=models.CharField(blank=True, default='', max_length=75),
        ),
        migrations.AddField(
            model_name='parents_sheet',
            name='child_development_no',
            field=models.CharField(blank=True, default='', max_length=75),
        ),
        migrations.AddField(
            model_name='parents_sheet',
            name='child_kindergarten',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='parents_sheet',
            name='child_school',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
