# Generated by Django 5.1.6 on 2025-04-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0014_remove_parents_sheet_child_school_which_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents_sheet',
            name='child_comments_1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='parents_sheet',
            name='child_comments_2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='parents_sheet',
            name='child_comments_3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='parents_sheet',
            name='child_comments_4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='parents_sheet',
            name='child_comments_5',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='parents_sheet',
            name='child_comments_6',
            field=models.TextField(blank=True, default=''),
        ),
    ]
