"""
Django settings for logopaedie project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import json
import os

from django.core.exceptions import ImproperlyConfigured


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4kq1sj_c6j!w8s9^-d+&te4#9l$v@1_hx4(p$r2logopaedie-^idy1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ckeditor',
    'ckeditor_uploader',
    'reports.apps.ReportsConfig',
    'parents.apps.ParentsConfig',
    'debug_toolbar',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'reports.middleware.IPAccessCheck',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]


ROOT_URLCONF = 'logopaedie.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'logopaedie.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'see local_settings',
        'USER': 'see local_settings',
        'PASSWORD': 'see local_settings',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'de'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Redirect to home URL after login (Default redirects to /accounts/profile/)
LOGIN_REDIRECT_URL = '/reports/'

#SESSION_EXPIRE_SECONDS = 900  # 900 - >15 minutes = 15 * 60
#SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True
#SESSION_EXPIRE_AT_BROWSER_CLOSE = True
#SESSION_SAVE_EVERY_REQUEST = True

# 30 * 60 = 30 Minuten + 5 Sekunden, damit die Session noch existiert, wenn nach 30 Minuten der Logout erfolgt
SESSION_EXPIRE_SECONDS = 30*60+5

#SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True
#SESSION_EXPIRE_AFTER_LAST_ACTIVITY_GRACE_PERIOD = 60 # group by minute

# Eingefügt nk 21.07.2019
#SESSION_EXPIRE_AT_BROWSER_CLOSE = True

#SESSION_TIMEOUT_REDIRECT = 'songarchiv/'

USE_X_FORWARDED_HOST = True

# Email settings
EMAIL_HOST = 'look at local_settings'
EMAIL_HOST_USER = 'look at local_settings'
EMAIL_HOST_PASSWORD = 'look at local_settings'
EMAIL_PORT = 'look at local_settings'
EMAIL_USE_TLS = 'look at local_settings'
#DEFAULT_FROM_EMAIL = ''

####################################
##  CKEDITOR CONFIGURATION ##
####################################

CKEDITOR_JQUERY_URL = 'https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js'

CKEDITOR_UPLOAD_PATH = 'uploads/'
CKEDITOR_IMAGE_BACKEND = "pillow"
CKEDITOR_CONFIGS = {'default':
                        {'height': 160,
                         'defaultLanguage': "de",
                         'scayt_autoStartup': True,
                         'scayt_sLang': "de_DE",
                         'coreStyles_bold': {'element': 'b', 'overrides': 'strong'},
                         'coreStyles_italic': {'element': 'i', 'overrides': 'em'},
                         'toolbar': 'Custom', 'toolbar_Custom':
                                 [
                                     ['Bold', 'Italic', 'Underline', 'BGColor', 'TextColor', 'BulletedList', 'Scayt', ],
                                 ],
                         },
                    'something':
                        {'height': 380,
                         'width': 800,
                         'defaultLanguage': "de",
                         'scayt_autoStartup': True,
                         'scayt_sLang': "de_DE",
                         'coreStyles_bold': {'element': 'b', 'overrides': 'strong'},
                         'coreStyles_italic': {'element': 'i', 'overrides': 'em'},
                         'toolbar': 'Custom', 'toolbar_Custom':
                             [
                                 ['Bold', 'Italic', 'Underline', 'BGColor', 'TextColor', 'BulletedList', 'Scayt', 'Source'],
                             ],
                         },
                    'waitlist':
                        {'height': 100,
                         'width': 540,
                         'defaultLanguage': "de",
                         'scayt_autoStartup': True,
                         'scayt_sLang': "de_DE",
                         'coreStyles_bold': {'element': 'b', 'overrides': 'strong'},
                         'coreStyles_italic': {'element': 'i', 'overrides': 'em'},
                         'toolbar': 'Custom', 'toolbar_Custom':
                             [
                                 ['Bold', 'Italic', 'Underline', 'BGColor', 'TextColor', 'BulletedList', 'Scayt',
                                  'Source'],
                             ],
                         }
                    }

###################################

# This must be the last part of the settings file

try:
    from .local_settings import *
except ImportError:
    print('There is no local settings, you must be on production')