# Generated by Django 2.2.3 on 2019-11-01 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name1', models.CharField(blank=True, default='', max_length=50)),
                ('doctor_name2', models.CharField(blank=True, default='', max_length=50)),
                ('doctor_street', models.CharField(blank=True, default='', max_length=50)),
                ('doctor_zip_code', models.CharField(blank=True, default='', max_length=5)),
                ('doctor_city', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('pa_title', models.CharField(blank=True, default='', max_length=50)),
                ('pa_address', models.CharField(choices=[('1', 'Frau'), ('2', 'Herr'), ('3', 'Firma')], default='1', max_length=1)),
                ('pa_first_name', models.CharField(max_length=50)),
                ('pa_last_name', models.CharField(max_length=50)),
                ('pa_street', models.CharField(max_length=100)),
                ('pa_zip_code', models.CharField(max_length=5)),
                ('pa_city', models.CharField(max_length=255)),
                ('pa_phone', models.CharField(blank=True, default='', max_length=20)),
                ('pa_cell_phone', models.CharField(blank=True, default='', max_length=20)),
                ('pa_date_of_birth', models.DateField(default='1900-01-01')),
                ('pa_gender', models.CharField(choices=[('1', 'weiblich'), ('2', 'männlich')], default='1', max_length=1)),
                ('pa_family_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Therapy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_date', models.DateField()),
                ('therapy_start', models.DateField(blank=True, default='', null=True)),
                ('therapy_end', models.DateField(blank=True, default='', null=True)),
                ('patients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Therapy_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(blank=True, default='', null=True)),
                ('therapy_current_result', models.TextField(default='')),
                ('therapy_emphases', models.TextField(default='')),
                ('therapy_forecast', models.TextField(default='')),
                ('therapy_indication_key', models.CharField(default='', max_length=10)),
                ('therapy_indicated', models.BooleanField(default='0')),
                ('therapy_break', models.BooleanField(default='0')),
                ('therapy_break_date', models.DateField(blank=True, default='', null=True)),
                ('therapy_success', models.BooleanField(default='0')),
                ('therapy_success_date', models.DateField(blank=True, default='', null=True)),
                ('therapy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Therapy')),
            ],
        ),
        migrations.CreateModel(
            name='Process_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_treatment', models.IntegerField()),
                ('process_content', models.CharField(max_length=255)),
                ('process_exercises', models.CharField(max_length=255)),
                ('process_results', models.CharField(max_length=255)),
                ('therapy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Therapy')),
            ],
        ),
    ]
