# Generated by Django 2.2.3 on 2019-12-18 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name1', models.CharField(blank=True, default='', max_length=50)),
                ('doctor_name2', models.CharField(blank=True, default='', max_length=50)),
                ('doctor_street', models.CharField(blank=True, default='', max_length=50)),
                ('doctor_zip_code', models.CharField(blank=True, default='', max_length=5)),
                ('doctor_city', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pa_first_name', models.CharField(max_length=50)),
                ('pa_last_name', models.CharField(max_length=50)),
                ('pa_street', models.CharField(max_length=100)),
                ('pa_city', models.CharField(max_length=255)),
                ('pa_phone', models.CharField(blank=True, default='', max_length=35, null=True)),
                ('pa_cell_phone', models.CharField(blank=True, default='', max_length=35, null=True)),
                ('pa_cell_phone_add1', models.CharField(blank=True, default='', max_length=35, null=True)),
                ('pa_cell_phone_add2', models.CharField(blank=True, default='', max_length=35, null=True)),
                ('pa_date_of_birth', models.DateField(default='1900-01-01')),
                ('pa_gender', models.CharField(choices=[('1', 'weiblich'), ('2', 'männlich')], default='1', max_length=1)),
                ('pa_attention', models.CharField(blank=True, default='', max_length=100)),
                ('pa_note', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp_first_name', models.CharField(blank=True, default='', max_length=50)),
                ('tp_last_name', models.CharField(blank=True, default='', max_length=50)),
                ('tp_initial', models.CharField(blank=True, default='', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Therapy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_date', models.DateField()),
                ('therapy_regulation_amount', models.IntegerField(blank=True, null=True)),
                ('therapy_duration', models.CharField(default='', max_length=10)),
                ('therapy_frequence', models.CharField(default='', max_length=5)),
                ('therapy_rid_of', models.BooleanField(default=False, null=True)),
                ('therapy_report_no_yes', models.BooleanField(default=True)),
                ('therapy_indication_key', models.CharField(default='', max_length=10)),
                ('therapy_icd_cod', models.CharField(default='', max_length=10)),
                ('patients', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='reports.Patient')),
                ('therapists', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Therapist')),
                ('therapy_doctor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='reports.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Therapy_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(blank=True, default='', null=True)),
                ('therapy_start', models.DateField(blank=True, default=None, null=True)),
                ('therapy_end', models.DateField(blank=True, default=None, null=True)),
                ('therapy_current_result', models.TextField(default='')),
                ('therapy_emphases', models.TextField(default='')),
                ('therapy_forecast', models.TextField(default='')),
                ('therapy_indicated', models.BooleanField(default=False)),
                ('therapy_break', models.BooleanField(default=False)),
                ('therapy_break_date', models.DateField(blank=True, default='', null=True)),
                ('therapy_comment', models.CharField(default='', max_length=50)),
                ('therapy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Therapy')),
            ],
        ),
        migrations.CreateModel(
            name='Process_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_treatment', models.IntegerField(default=0)),
                ('process_content', models.CharField(blank=True, default='', max_length=255)),
                ('process_exercises', models.CharField(blank=True, default='', max_length=50)),
                ('process_results', models.CharField(blank=True, default='', max_length=50)),
                ('process_content_2', models.CharField(blank=True, default='', max_length=255)),
                ('process_exercises_2', models.CharField(blank=True, default='', max_length=50)),
                ('process_results_2', models.CharField(blank=True, default='', max_length=50)),
                ('process_content_3', models.CharField(blank=True, default='', max_length=255)),
                ('process_exercises_3', models.CharField(blank=True, default='', max_length=50)),
                ('process_results_3', models.CharField(blank=True, default='', max_length=50)),
                ('therapy', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='reports.Therapy')),
            ],
        ),
        migrations.CreateModel(
            name='InitialAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ia_date', models.DateField(blank=True, default='', null=True)),
                ('ia_assessment', models.CharField(blank=True, default='', max_length=100)),
                ('ia_artikulation', models.CharField(blank=True, default='', max_length=100)),
                ('ia_syntax', models.CharField(blank=True, default='', max_length=100)),
                ('ia_semantik', models.CharField(blank=True, default='', max_length=100)),
                ('ia_understanding', models.CharField(blank=True, default='', max_length=100)),
                ('ia_expiration', models.CharField(blank=True, default='', max_length=100)),
                ('ia_motor_skills', models.CharField(blank=True, default='', max_length=100)),
                ('ia_perception', models.CharField(blank=True, default='', max_length=100)),
                ('ia_breathing', models.CharField(blank=True, default='', max_length=100)),
                ('ia_other', models.CharField(blank=True, default='', max_length=100)),
                ('ia_test', models.CharField(blank=True, default='', max_length=100)),
                ('ia_test_date', models.DateField(blank=True, default='', null=True)),
                ('ia_test_result', models.CharField(choices=[('1', 'sehr gut'), ('2', 'gut'), ('3', 'befriedigend'), ('4', 'schlecht'), ('5', 'sehr schlecht')], default='1', max_length=1)),
                ('therapy', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='reports.Therapy')),
            ],
        ),
    ]
