# Generated by Django 3.0.8 on 2020-12-27 16:12

from django_ckeditor_5.fields import CKEditor5Field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialassessment',
            name='ia_first_diagnostic',
            field=CKEditor5Field(),
        ),
    ]
