# Generated by Django 2.2.3 on 2019-07-21 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('pa_first_name', models.CharField(max_length=50)),
                ('pa_last_name', models.CharField(max_length=50)),
                ('pa_street', models.CharField(max_length=100)),
                ('pa_zip_code', models.CharField(max_length=5)),
                ('pa_city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='therapy_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.CharField(max_length=8)),
                ('diagnostic_1', models.CharField(max_length=255)),
                ('diagonstic_2', models.CharField(max_length=255)),
                ('patients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.patients')),
            ],
        ),
        migrations.CreateModel(
            name='process_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.CharField(max_length=8)),
                ('diagnostic_1', models.CharField(max_length=255)),
                ('diagonstic_2', models.CharField(max_length=255)),
                ('patients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.patients')),
            ],
        ),
    ]
