# Generated by Django 3.0.8 on 2020-12-23 12:29

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostic_key', models.CharField(default=True, max_length=10, unique=True)),
                ('diagnostic_description', models.CharField(default=False, max_length=250)),
                ('diagnostic_max_therapy', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to=reports.models.dynamik_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document_therapy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to=reports.models.dynamik_path_therapy)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Login_Failed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.CharField(blank=True, default='', max_length=100)),
                ('user_name', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Something',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pa_something_else', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Therapy_Something',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('something_else', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_lanr',
            field=models.CharField(default='', max_length=9, unique=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_name3',
            field=models.CharField(blank=True, default='', max_length=75),
        ),
        migrations.AddField(
            model_name='doctor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='initialassessment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initialassessment',
            name='ia_dysphagie',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='initialassessment',
            name='ia_enhancement',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='initialassessment',
            name='ia_information',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='initialassessment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='pa_active_no_yes',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='pa_allergy',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='pa_cell_phone_sms',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='pa_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='patient',
            name='pa_zip_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='process_report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process_report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='therapist',
            name='tp_user_logopakt',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='therapist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='therapy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='therapy',
            name='therapy_homevisit_no_yes',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='therapy',
            name='therapy_icd_cod_2',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='therapy',
            name='therapy_icd_cod_3',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='therapy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='therapy_report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='therapy_report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_name1',
            field=models.CharField(blank=True, default='', max_length=75),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_name2',
            field=models.CharField(blank=True, default='', max_length=75),
        ),
        migrations.AlterField(
            model_name='initialassessment',
            name='ia_test_result',
            field=models.CharField(choices=[('1', 'sehr gut'), ('2', 'gut'), ('3', 'befriedigend'), ('4', 'schlecht'), ('5', 'sehr schlecht'), ('6', 'nicht auswertbar')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pa_cell_phone',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pa_cell_phone_add1',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pa_cell_phone_add2',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pa_phone',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='process_report',
            name='process_exercises',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='process_report',
            name='process_exercises_2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='process_report',
            name='process_exercises_3',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='therapy',
            name='therapists',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.Therapist'),
        ),
        migrations.AlterField(
            model_name='therapy',
            name='therapy_report_no_yes',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='therapy_report',
            name='therapy_comment',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='therapy_report',
            name='therapy_current_result',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='therapy_report',
            name='therapy_emphases',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='therapy_report',
            name='therapy_forecast',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('pa_first_name', 'pa_last_name', 'pa_date_of_birth'), name='unique pa_name'),
        ),
        migrations.AddField(
            model_name='therapy_something',
            name='therapy',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='reports.Therapy'),
        ),
        migrations.AddField(
            model_name='patient_something',
            name='patient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='reports.Patient'),
        ),
        migrations.AddField(
            model_name='document_therapy',
            name='therapy',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='reports.Therapy'),
        ),
        migrations.AddField(
            model_name='document',
            name='patient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='reports.Patient'),
        ),
        migrations.AddField(
            model_name='therapy',
            name='diagnostic_group',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.Diagnostic_group'),
        ),
    ]
