# Generated by Django 3.0.1 on 2019-12-30 13:51

from django.db import migrations, models
import django.db.models.deletion
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=reports.models.dynamik_path),
        ),
        migrations.CreateModel(
            name='Therapy_Something',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('something_else', models.TextField()),
                ('therapy', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='reports.Therapy')),
            ],
        ),
    ]
