# Generated by Django 2.2.3 on 2019-07-21 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_patients_process_report_therapy_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_report',
            name='patients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Patients'),
        ),
        migrations.AlterField(
            model_name='therapy_report',
            name='patients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Patients'),
        ),
    ]
