# Generated by Django 2.2.3 on 2019-11-15 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_patient_patient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='pa_address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='pa_title',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='pa_zip_code',
        ),
    ]
