# Generated by Django 3.0.8 on 2020-12-23 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20201223_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapy',
            name='diagnostic_group',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.Diagnostic_group'),
        ),
    ]
