# Generated by Django 3.0.8 on 2020-12-29 06:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initialassessment_ia_first_diagnostic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialassessment',
            name='ia_first_diagnostic',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
