# Generated by Django 2.2.3 on 2019-07-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('reports', '0003_auto_20190721_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('pa_first_name', models.CharField(max_length=50)),
                ('pa_last_name', models.CharField(max_length=50)),
                ('pa_street', models.CharField(max_length=100)),
                ('pa_zip_code', models.CharField(max_length=5)),
                ('pa_city', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='patients',
            new_name='Patient',
        ),
    ]
