# Generated by Django 3.0.8 on 2020-12-29 06:58

from django_ckeditor_5.fields import CKEditor5Field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20201229_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialassessment',
            name='ia_first_diagnostic',
            field=CKEditor5Field(),
        ),
    ]
