# Generated by Django 3.0.1 on 2019-12-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20191230_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_lanr',
            field=models.CharField(default='999999999', max_length=9),
        ),
    ]
