# Generated by Django 2.2.3 on 2019-11-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20191115_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapy',
            name='therapy_duration',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='therapy',
            name='therapy_icd_cod',
            field=models.TextField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='therapy',
            name='therapy_indication_key',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='therapy',
            name='therapy_regulation_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
