# Generated by Django 2.2.3 on 2019-08-17 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20190721_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='pa_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='reports.Address'),
        ),
    ]
