# Generated by Django 3.0.1 on 2020-01-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_doctor_doctor_lanr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_name1',
            field=models.CharField(blank=True, default='', max_length=75),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_name2',
            field=models.CharField(blank=True, default='', max_length=75),
        ),
    ]
