# Generated by Django 2.2.3 on 2019-11-16 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20191116_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapy',
            name='therapy_doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reports.Doctor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='therapy',
            name='therapy_icd_cod',
            field=models.CharField(default='', max_length=10),
        ),
    ]
