# Generated by Django 3.0.8 on 2020-12-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20201229_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapy',
            name='first_diagnostic_no_yes',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='therapy',
            name='need_diagnostic_no_yes',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
