# Generated by Django 3.0.8 on 2021-01-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20201230_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapy_report',
            name='therapy_another',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='therapy_report',
            name='therapy_another_text',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='therapy_report',
            name='therapy_finish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='therapy_report',
            name='therapy_frequence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='therapy_report',
            name='therapy_frequence_count_per_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='therapy_report',
            name='therapy_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='therapy_report',
            name='therapy_group_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='therapy_report',
            name='therapy_home_visit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='therapy_report',
            name='therapy_individual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='therapy_report',
            name='therapy_individual_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='therapy_report',
            name='therapy_re_introduction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='therapy_report',
            name='therapy_re_introduction_weeks',
            field=models.IntegerField(default=0),
        ),
    ]
