# Generated by Django 2.2.3 on 2019-08-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20190817_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pa_address',
            field=models.CharField(choices=[('1', 'Frau'), ('2', 'Herr'), ('3', 'Firma')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
