# Generated by Django 3.0.1 on 2020-01-10 15:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20200105_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapy_something',
            name='something_else',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
