# Generated by Django 2.2.3 on 2019-11-23 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20191116_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapy_report',
            name='therapy_indication_key',
        ),
    ]
