# Generated by Django 3.0.1 on 2020-01-10 15:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20200110_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapy_report',
            name='therapy_current_result',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='therapy_report',
            name='therapy_emphases',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='therapy_report',
            name='therapy_forecast',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
