# Generated by Django 3.0.8 on 2021-01-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20210104_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapy_report',
            name='therapy_frequence_count_per_week',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='therapy_report',
            name='therapy_group_min',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='therapy_report',
            name='therapy_individual_min',
            field=models.CharField(default='', max_length=10),
        ),
    ]
