# Generated by Django 2.2.3 on 2019-11-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_remove_therapy_report_therapy_indication_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapy_report',
            name='therapy_break',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='therapy_report',
            name='therapy_indicated',
            field=models.BooleanField(default=False),
        ),
    ]
