# Generated by Django 3.0.1 on 2020-01-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20200110_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapy',
            name='therapy_report_no_yes',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
