# Generated by Django 3.0.8 on 2021-01-06 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20210105_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapy_report',
            name='therapy_re_introduction',
        ),
        migrations.RemoveField(
            model_name='therapy_report',
            name='therapy_re_introduction_weeks',
        ),
    ]
