# Generated by Django 2.2.3 on 2019-08-18 09:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20190817_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='therapy_report',
            old_name='diagnostic_1',
            new_name='therapy_content',
        ),
        migrations.RenameField(
            model_name='therapy_report',
            old_name='diagonstic_2',
            new_name='therapy_exercises',
        ),
        migrations.RemoveField(
            model_name='therapy_report',
            name='patients',
        ),
        migrations.AddField(
            model_name='therapy_report',
            name='therapy_results',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='therapy_report',
            name='treatment',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='therapy_report',
            name='report_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Therapy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_date', models.DateField()),
                ('therapy_start', models.DateField()),
                ('therapy_end', models.DateField()),
                ('patients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='therapy_report',
            name='therapy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reports.Therapy'),
            preserve_default=False,
        ),
    ]
