# Generated by Django 3.0.8 on 2021-01-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20210106_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialassessment',
            name='ia_diagnostic_level',
            field=models.CharField(choices=[('ED', 'Erst-Diagnostik'), ('BD', 'Bedarfs-Diagnostik'), ('WD', 'Weiterführende-Diagnostik')], default='ED', max_length=2),
        ),
    ]
