# Generated by Django 3.0.1 on 2020-01-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20200111_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialassessment',
            name='ia_enhancement',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='initialassessment',
            name='ia_need',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='initialassessment',
            name='ia_test_result',
            field=models.CharField(choices=[('1', 'sehr gut'), ('2', 'gut'), ('3', 'befriedigend'), ('4', 'schlecht'), ('5', 'sehr schlecht'), ('6', 'nicht auswertbar')], default='1', max_length=1),
        ),
    ]
