# Generated by Django 2.2.3 on 2019-12-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20191123_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pa_attention',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='pa_cell_phone_add1',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='patient',
            name='pa_cell_phone_add2',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='patient',
            name='pa_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pa_cell_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pa_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
