# Generated by Django 3.0.1 on 2020-01-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20200111_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_name3',
            field=models.CharField(blank=True, default='', max_length=75),
        ),
    ]
