# Generated by Django 2.2.3 on 2019-12-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20191201_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pa_attention',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
