# Generated by Django 3.0.8 on 2021-01-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_initialassessment_ia_diagnostic_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapy',
            name='continue_diagnostic_no_yes',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
