# Generated by Django 2.2.3 on 2019-09-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20190818_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pa_geburtsdatum',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
