# Generated by Django 2.2.3 on 2019-12-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_auto_20191206_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pa_cell_phone',
            field=models.CharField(blank=True, default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pa_cell_phone_add1',
            field=models.CharField(blank=True, default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pa_cell_phone_add2',
            field=models.CharField(blank=True, default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pa_phone',
            field=models.CharField(blank=True, default='', max_length=35),
        ),
    ]
