# Generated by Django 2.2.3 on 2019-09-14 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_patient_pa_geburtsdatum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='pa_geburtsdatum',
            new_name='pa_date_of_birth',
        ),
    ]
