# Generated by Django 3.0.8 on 2021-01-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_auto_20210106_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapy_report',
            name='therapy_break_date',
            field=models.DateField(blank=True, default='1900-01-01', null=True),
        ),
    ]
