# Generated by Django 2.2.3 on 2019-12-07 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_auto_20191207_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='pa_family_doctor',
        ),
    ]
