# Generated by Django 3.0.1 on 2020-01-13 12:03

from django.db import migrations, models
import django.db.models.deletion
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_auto_20200112_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document_therapy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to=reports.models.dynamik_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('therapy', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='reports.Therapy')),
            ],
        ),
    ]
