# Generated by Django 2.2.3 on 2019-12-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_remove_patient_pa_family_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapy',
            name='therapy_frequence',
            field=models.CharField(default='', max_length=5),
        ),
    ]
