# Generated by Django 2.2.3 on 2019-09-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_auto_20190914_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pa_cell_phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pa_phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
