# Generated by Django 3.0.1 on 2020-01-13 12:42

from django.db import migrations, models
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_document_therapy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_therapy',
            name='document',
            field=models.FileField(upload_to=reports.models.dynamik_path_therapy),
        ),
    ]
