# Generated by Django 2.2.3 on 2019-12-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_therapy_therapy_frequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapy',
            name='therapy_rid_of',
            field=models.BooleanField(default=False),
        ),
    ]
