# Generated by Django 3.0.8 on 2021-01-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_auto_20210108_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pa_email_no_yes',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='pa_invoice_mail',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='pa_sms_no_yes',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
