# Generated by Django 3.0.1 on 2020-01-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_auto_20200119_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pa_cell_phone',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pa_cell_phone_add1',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pa_cell_phone_add2',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pa_phone',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
