# Generated by Django 2.2.3 on 2019-10-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_auto_20190914_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapy',
            name='therapy_end',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='therapy',
            name='therapy_start',
            field=models.DateField(blank=True),
        ),
    ]
