# Generated by Django 3.0.1 on 2020-01-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_auto_20200119_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pa_allergy',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
