# Generated by Django 3.0.8 on 2021-01-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_therapy_report_therapy_necessary'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapy_report',
            name='therapy_break_end',
            field=models.BooleanField(default=False),
        ),
    ]
