# Generated by Django 3.0.8 on 2021-01-26 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_therapy_report_therapy_break_end'),
    ]

    operations = [
        migrations.RenameField(
            model_name='therapy_report',
            old_name='therapy_break_end',
            new_name='therapy_break_internal',
        ),
    ]
