# Generated by Django 2.2.3 on 2019-10-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_auto_20191006_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapy',
            name='therapy_end',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='therapy',
            name='therapy_start',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
