# Generated by Django 2.2.3 on 2019-12-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_auto_20191208_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_report',
            name='process_content_2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='process_report',
            name='process_content_3',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='process_report',
            name='process_exercises_2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='process_report',
            name='process_exercises_3',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='process_report',
            name='process_results_2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='process_report',
            name='process_results_3',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='process_report',
            name='process_exercises',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='process_report',
            name='process_results',
            field=models.CharField(max_length=50),
        ),
    ]
