# Generated by Django 3.0.1 on 2020-01-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_therapy_therapy_homevisit_no_yes'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('pa_first_name', 'pa_last_name', 'pa_date_of_birth'), name='unique pa_name'),
        ),
    ]
