# Generated by Django 2.2.3 on 2019-12-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_auto_20191211_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_report',
            name='process_content',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='process_report',
            name='process_exercises',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='process_report',
            name='process_results',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
