# Generated by Django 3.0.8 on 2021-11-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_auto_20210126_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wait_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wl_active', models.BooleanField(default=True, null=True)),
                ('wl_first_name', models.CharField(max_length=50)),
                ('wl_last_name', models.CharField(max_length=50)),
                ('wl_street', models.CharField(max_length=100)),
                ('wl_zip_code', models.CharField(default='', max_length=10)),
                ('wl_city', models.CharField(max_length=255)),
                ('wl_phone', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('wl_cell_phone', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('wl_cell_phone_add1', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('wl_cell_phone_add2', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('wl_cell_phone_sms', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('wl_email', models.EmailField(blank=True, max_length=254)),
                ('wl_date_of_birth', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('wl_gender', models.CharField(choices=[('1', 'weiblich'), ('2', 'männlich')], default='1', max_length=1)),
                ('wl_call_date', models.DateField(default='1900-01-01')),
                ('wl_call_for', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('wl_contact_person', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('wl_information', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('wl_diagnostic', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('wl_appointment', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('wl_insurance', models.CharField(choices=[('1', 'unbekannt'), ('2', 'gesetzlich'), ('3', 'privat')], default='1', max_length=1)),
                ('wl_recipe', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
    ]
