# Generated by Django 3.0.1 on 2020-01-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_auto_20200125_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_report',
            name='process_exercises',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='process_report',
            name='process_exercises_2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='process_report',
            name='process_exercises_3',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
