# Generated by Django 3.0.8 on 2021-11-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_wait_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wait_list',
            name='wl_zip_code',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
