# Generated by Django 2.2.3 on 2019-12-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_auto_20191212_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapy',
            name='therapy_rid_of',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
