# Generated by Django 3.0.1 on 2020-01-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_auto_20200125_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pa_active_no_yes',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
