# Generated by Django 2.2.3 on 2019-12-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_auto_20191213_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapy_report',
            name='therapy_start',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
