# Generated by Django 3.0.1 on 2020-02-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_patient_pa_active_no_yes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initialassessment',
            name='ia_need',
        ),
        migrations.AddField(
            model_name='initialassessment',
            name='ia_information',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
