# Generated by Django 2.2.3 on 2019-12-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_therapy_report_therapy_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapy_report',
            name='therapy_end',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
