# Generated by Django 3.0.1 on 2020-02-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0021_auto_20200209_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='tp_user_logopakt',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
