# Generated by Django 2.2.3 on 2019-12-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0021_therapy_report_therapy_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapy',
            name='therapy_end',
        ),
        migrations.RemoveField(
            model_name='therapy',
            name='therapy_start',
        ),
        migrations.AlterField(
            model_name='patient',
            name='pa_cell_phone',
            field=models.CharField(blank=True, default='', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pa_cell_phone_add1',
            field=models.CharField(blank=True, default='', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pa_cell_phone_add2',
            field=models.CharField(blank=True, default='', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pa_phone',
            field=models.CharField(blank=True, default='', max_length=35, null=True),
        ),
    ]
