# Generated by Django 3.0.1 on 2020-02-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0022_therapist_tp_user_logopakt'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialassessment',
            name='ia_dysphagie',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='pa_zip_code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
