# Generated by Django 3.0.1 on 2020-02-15 05:58

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0023_auto_20200214_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_Something',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pa_something_else', ckeditor.fields.RichTextField()),
                ('patient', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='reports.Patient')),
            ],
        ),
    ]
