# Generated by Django 3.2.9 on 2021-12-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0025_shortcuts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wait_list',
            name='wl_information',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
