# Generated by Django 3.2.9 on 2021-12-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0027_auto_20211202_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapy_report',
            name='therapy_report_variation',
            field=models.IntegerField(default=0),
        ),
    ]
