# Generated by Django 3.0.1 on 2020-03-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0030_login_failed'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pa_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
