# Generated by Django 3.2.9 on 2021-12-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0032_therapy_report_therapy_therapist_diagnostic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapy_report',
            name='therapy_report_variation',
            field=models.IntegerField(default=0),
        ),
    ]
