# Generated by Django 3.2.9 on 2021-12-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0033_alter_therapy_report_therapy_report_variation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_User_Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, default='', max_length=100)),
                ('ip_address', models.CharField(blank=True, default='', max_length=100)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
