# Generated by Django 3.2.9 on 2022-06-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0034_login_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='parents_form',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='registration_form',
            field=models.BooleanField(default=False),
        ),
    ]
