# Generated by Django 5.1.4 on 2025-02-07 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0037_alter_initialassessment_ia_first_diagnostic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapy_report',
            name='therapy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reports.therapy'),
        ),
    ]
