# Generated by Django 5.1.4 on 2025-02-07 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0038_alter_therapy_report_therapy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialassessment',
            name='therapy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reports.therapy'),
        ),
    ]
