# Generated by Django 5.1.6 on 2025-02-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0039_alter_initialassessment_therapy'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapy',
            name='therapy_rid_of_method',
            field=models.CharField(choices=[('0', 'keine Auswahl'), ('1', 'per Post'), ('2', 'per Mail'), ('3', 'Therapeut kassiert mitgeben'), ('4', 'RG. Therap. mitgeben ohne kassieren')], default='0', max_length=1),
        ),
    ]
