# Generated by Django 5.1.6 on 2025-02-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0041_alter_therapy_therapy_rid_of_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapy',
            name='therapy_rid_of_method',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
