# Generated by Django 5.1.6 on 2025-03-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0042_alter_therapy_therapy_rid_of_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_name', models.CharField(default='', max_length=50, null=True)),
                ('reg_first_name', models.CharField(default='', max_length=50, null=True)),
                ('reg_street', models.CharField(default='', max_length=100, null=True)),
                ('reg_zip_code', models.CharField(default='', max_length=10, null=True)),
                ('reg_city', models.CharField(default='', max_length=255, null=True)),
                ('reg_date_of_birth', models.DateField(default='1900-01-01')),
                ('reg_doctor', models.CharField(default='', max_length=100, null=True)),
                ('reg_phone', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('reg_cell_phone', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('reg_email', models.EmailField(blank=True, max_length=254)),
                ('reg_signature', models.ImageField(upload_to='signatures/')),
                ('reg_created', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
