# Generated by Django 5.1.6 on 2025-03-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0043_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.AddField(
            model_name='wait_list',
            name='wl_di',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='wait_list',
            name='wl_do',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='wait_list',
            name='wl_fr',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='wait_list',
            name='wl_mi',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='wait_list',
            name='wl_mo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='wait_list',
            name='wl_sa',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
