# Generated by Django 5.1.6 on 2025-03-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0044_delete_registration_wait_list_wl_di_wait_list_wl_do_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pa_appointment',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='pa_di',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='pa_do',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='pa_fr',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='pa_mi',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='pa_mo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='pa_sa',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
