# Generated by Django 5.1.6 on 2025-03-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0046_registration_patient_pa_wiedervorstellung_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pa_wiedervorstellung_info',
            field=models.CharField(default='', max_length=254, null=True),
        ),
    ]
