# Generated by Django 6.0.2 on 2026-09-13 09:31

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0049_historicalinitialassessment_historicalpatient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinitialassessment',
            name='ia_first_diagnostic',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='initialassessment',
            name='ia_first_diagnostic',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='Text'),
        ),
    ]
