# Generated by Django 6.0.2 on 2026-09-13 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0050_alter_historicalinitialassessment_ia_first_diagnostic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalregistration',
            name='reg_doctor',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='reg_doctor',
        ),
    ]
