# Generated by Django 6.0.2 on 2026-09-13 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0051_remove_historicalregistration_reg_doctor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shortcuts',
        ),
    ]
