# Generated by Django 6.0.2 on 2026-09-13 15:56

from django.db import migrations, models


def deduplicate_login_user_agent(apps, schema_editor):
    """Entfernt doppelte (user_name, ip_address, user_agent)-Kombinationen, die durch den
    fehlenden user_name-Filter in post_login() entstanden sind, bevor die UniqueConstraint
    greift. Behalten wird jeweils der zuletzt gesehene Datensatz."""
    Login_User_Agent = apps.get_model('reports', 'Login_User_Agent')
    seen = set()
    for entry in Login_User_Agent.objects.order_by('-last_login', '-id'):
        key = (entry.user_name, entry.ip_address, entry.user_agent)
        if key in seen:
            entry.delete()
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0052_delete_shortcuts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_user_agent',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(deduplicate_login_user_agent, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='login_user_agent',
            constraint=models.UniqueConstraint(fields=('user_name', 'ip_address', 'user_agent'), name='unique login_user_agent'),
        ),
    ]
