from django.db import models

class Parents_sheet(models.Model):

    AGEADVICE_CHOICES = [
        ('unbekannt', 'keine Auswahl'),
        ('verspaetet', 'verspätet'),
        ('altersgerecht', 'altersgerecht'),
    ]

    LANGUAGEUSE_CHOICES = [
        ('viel', 'viel'),
        ('weniger', 'weniger'),
        ('kaum', 'kaum'),
        ('gar_nicht', 'gar nicht'),
    ]

    child_session_id = models.CharField(max_length=75, blank=True, default='')
    child_last_name = models.CharField(max_length=75, blank=True, default='')
    child_first_name = models.CharField(max_length=75, blank=True, default='')
    child_day_of_birth = models.DateField(default='2000-01-01', blank=True, null=True)
    health_assurance = models.CharField(max_length=75, blank=True, default='')
    doctor = models.CharField(max_length=75, blank=True, default='')
    phone = models.CharField(max_length=75, blank=True, default='')
    cellphone = models.CharField(max_length=75, blank=True, default='')
    phone_work = models.CharField(max_length=75, blank=True, default='')
    email = models.CharField(max_length=75, blank=True, default='')
    mother_last_name = models.CharField(max_length=75, blank=True, default='')
    mother_first_name = models.CharField(max_length=75, blank=True, default='')
    mother_day_of_birth = models.DateField(default='1950-01-01', blank=True, null=True)
    mother_job = models.CharField(max_length=75, blank=True, default='')
    father_last_name = models.CharField(max_length=75, blank=True, default='')
    father_first_name = models.CharField(max_length=75, blank=True, default='')
    father_day_of_birth = models.DateField(default='1950-01-01', blank=True, null=True)
    father_job = models.CharField(max_length=75, blank=True, default='')
    siblings1_last_name = models.CharField(max_length=75, blank=True, default='')
    siblings1_first_name = models.CharField(max_length=75, blank=True, default='')
    siblings1_age = models.CharField(max_length=75, blank=True, default='')
    siblings2_last_name = models.CharField(max_length=75, blank=True, default='')
    siblings2_first_name = models.CharField(max_length=75, blank=True, default='')
    siblings2_age = models.CharField(max_length=75, blank=True, default='')
    siblings3_last_name = models.CharField(max_length=75, blank=True, default='')
    siblings3_first_name = models.CharField(max_length=75, blank=True, default='')
    siblings3_age = models.CharField(max_length=75, blank=True, default='')
    problems_pregnancy   = models.BooleanField(default=True, null=True)
    problems_pregnancy_yes = models.CharField(max_length=75, blank=True, default='')
    problems_family_speak_listen   = models.BooleanField(default=True, null=True)
    problems_family_speak_listen_yes = models.CharField(max_length=75, blank=True, default='')
    child_allergy   = models.BooleanField(default=True, null=True)
    child_allergy_yes = models.CharField(max_length=75, blank=True, default='')
    crawl_age = models.CharField(max_length=75, blank=True, default='')
    crawl_age_advise = models.CharField(max_length=20, choices=AGEADVICE_CHOICES, default='unbekannt')
    walk_age = models.CharField(max_length=75, blank=True, default='')
    walk_age_advise = models.CharField(max_length=20, choices=AGEADVICE_CHOICES, default='unbekannt')
    child_dev_1 = models.CharField(max_length=75, blank=True, default='')
    child_dev_2 = models.CharField(max_length=75, blank=True, default='')
    child_dev_3 = models.CharField(max_length=75, blank=True, default='')
    child_dev_4 = models.CharField(max_length=75, blank=True, default='')
    child_dev_language = models.BooleanField(default=True, null=True)
    child_dev_language_yes = models.CharField(max_length=75, blank=True, default='')
    child_dev_5 = models.BooleanField(default=True, null=True)
    child_dev_5_yes = models.CharField(max_length=75, blank=True, default='')
    child_left_handed = models.BooleanField(default=True, null=True)
    child_chronic_disease = models.BooleanField(default=True, null=True)
    child_chronic_disease_yes = models.CharField(max_length=75, blank=True, default='')
    child_nutrition = models.CharField(max_length=75, blank=True, default='')
    child_hospital_visits = models.BooleanField(default=True, null=True)
    child_hospital_visits_yes = models.CharField(max_length=75, blank=True, default='')
    child_medicine = models.BooleanField(default=True, null=True)
    child_medicine_yes = models.CharField(max_length=75, blank=True, default='')
    child_count_colds = models.CharField(max_length=75, blank=True, default='')
    child_timpani_tube = models.BooleanField(default=True, null=True)
    child_listen = models.BooleanField(default=True, null=True)
    child_illness_1 = models.BooleanField(default=True, null=True)
    child_illness_2 = models.BooleanField(default=True, null=True)
    child_what_teething = models.CharField(max_length=75, blank=True, default='')
    child_glases = models.BooleanField(default=True, null=True)
    child_hearing_aid = models.BooleanField(default=True, null=True)
    child_problems_sleeping_hearing = models.BooleanField(default=True, null=True)
    child_problems_sleeping_hearing_yes = models.CharField(max_length=75, blank=True, default='')
    child_use_of_language = models.CharField(max_length=20, choices=LANGUAGEUSE_CHOICES, default='weniger')
    child_speaking_interrupt = models.BooleanField(default=True, null=True)
    child_speaking_interrupt_yes = models.CharField(max_length=75, blank=True, default='')
    child_speaking_dev = models.BooleanField(default=True, null=True)
    child_speaking_dev_yes = models.CharField(max_length=75, blank=True, default='')
    child_mimik = models.BooleanField(default=False, null=True)
    child_understanding = models.BooleanField(default=False, null=True)
    child_stranger = models.BooleanField(default=False, null=True)
    child_gestik = models.BooleanField(default=False, null=True)
    child_letter_wrong = models.BooleanField(default=True, null=True)
    child_letter_wrong_yes = models.CharField(max_length=75, blank=True, default='')
    child_sentence_construction = models.BooleanField(default=True, null=True)
    child_speech = models.BooleanField(default=True, null=True)
    child_noises_reaktion = models.BooleanField(default=True, null=True)
    child_watch_contact = models.BooleanField(default=True, null=True)
    child_talking = models.BooleanField(default=True, null=True)
    child_stutter = models.BooleanField(default=True, null=True)
    child_development = models.BooleanField(default=True, null=True)
    child_development_no = models.CharField(max_length=75, blank=True, default='')
    child_playing_1 = models.BooleanField(default=True, null=True)
    child_playing_2 = models.BooleanField(default=True, null=True)
    child_playing_3 = models.CharField(max_length=75, blank=True, default='')
    child_school = models.BooleanField(default=False, null=True)
    child_kindergarten = models.BooleanField(default=False, null=True)
    child_caregivers = models.CharField(max_length=75, blank=True, default='')
    child_speech_therapy = models.BooleanField(default=True, null=True)
    child_speech_therapy_yes = models.CharField(max_length=75, blank=True, default='')
    child_speech_therapy_advise = models.CharField(max_length=254, blank=True, default='')
    child_comments_1 = models.CharField(max_length=255, blank=True, default='')
    child_comments_2 = models.CharField(max_length=255, blank=True, default='')
    child_comments_3 = models.CharField(max_length=255, blank=True, default='')
    child_comments_4 = models.CharField(max_length=255, blank=True, default='')
    child_comments_5 = models.CharField(max_length=255, blank=True, default='')
    child_comments_6 = models.CharField(max_length=255, blank=True, default='')
    sheet_created = models.BooleanField(default=False, null=True)

    def __str__(self):
        return self.child_last_name + ", " + self.child_first_name